  // Copyright 2019 Arisova Anastasiia
#ifndef MODULES_TASK_3_ARISOVA_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_
#define MODULES_TASK_3_ARISOVA_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_

double goParallelAlgorithm(double a, double b, double(*Q)(double));

#endif  // MODULES_TASK_3_ARISOVA_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_
