  // Copyright 2019 Arisova Anastasiia
#ifndef MODULES_TASK_2_ARISOVA_A_SLEEPING_BARBER_SLEEPING_BARBER_H_
#define MODULES_TASK_2_ARISOVA_A_SLEEPING_BARBER_SLEEPING_BARBER_H_

int BarberShop(int R, int size_queue);

#endif  // MODULES_TASK_2_ARISOVA_A_SLEEPING_BARBER_SLEEPING_BARBER_H_
