// Copyright 2019 Evdokimov Artem
#ifndef MODULES_TASK_2_EVDOKIMOV_A_PHILOSOPHERS_PHILOSOPHERS_H_
#define MODULES_TASK_2_EVDOKIMOV_A_PHILOSOPHERS_PHILOSOPHERS_H_

void philosophersHasLunch(int, int);

#endif  // MODULES_TASK_2_EVDOKIMOV_A_PHILOSOPHERS_PHILOSOPHERS_H_
