// Copyright 2019 Kudryashov Nikita
#ifndef MODULES_TASK_2_KUDRYASHOV_N_HYPERCUBE_TOPOLOGY_HYPERCUBE_H_
#define MODULES_TASK_2_KUDRYASHOV_N_HYPERCUBE_TOPOLOGY_HYPERCUBE_H_

#include <mpi.h>

MPI_Comm createHcube(unsigned int dim);

#endif  // MODULES_TASK_2_KUDRYASHOV_N_HYPERCUBE_TOPOLOGY_HYPERCUBE_H_
