// Copyright 2019 Mazur Daniil
#ifndef MODULES_TASK_2_MAZUR_D_READER_WRITER_READER_WRITER_H_
#define MODULES_TASK_2_MAZUR_D_READER_WRITER_READER_WRITER_H_

int startTask(int writersCount);

#endif  // MODULES_TASK_2_MAZUR_D_READER_WRITER_READER_WRITER_H_
