#ifndef MODULES_TASK_1_KORNEV_N_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_
#define MODULES_TASK_1_KORNEV_N_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_

// Copyright 2019 Kornev Nikita

#include <vector>

std::vector<int> getRandVect(int n);
int single_find(std::vector<int> v);
int mpi_find(std::vector<int> v);

#endif  // MODULES_TASK_1_KORNEV_N_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_
